apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    app: cuda-ipc-consumer
spec:
  hostIPC: true
  hostPID: true
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-a100
  containers:
  - name: consumer
    image: quay.io/harpatil/cuda-ipc:latest
    command: ["/usr/local/bin/consumer", "1"]
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      privileged: true
      capabilities:
        add: ["IPC_LOCK"]
