apiVersion: v1
kind: Pod
metadata:
  name: producer
spec:
  hostIPC: true
  nodeSelector:
    cloud.google.com/gke-gpu: "true"  # Adjust this selector based on your cluster setup
  containers:
  - name: producer
    image: quay.io/harpatil/cuda-ipc:latest
    command: ["/usr/local/bin/producer"]
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      capabilities:
        add: ["IPC_LOCK"]
---
apiVersion: v1
kind: Pod
metadata:
  name: consumer
spec:
  hostIPC: true
  nodeSelector:
    cloud.google.com/gke-gpu: "true"  # Adjust this selector based on your cluster setup
  containers:
  - name: consumer
    image: quay.io/harpatil/cuda-ipc:latest
    command: ["/usr/local/bin/consumer"]
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      capabilities:
        add: ["IPC_LOCK"]