apiVersion: v1
kind: Pod
metadata:
  name: producer
  labels:
    app: cuda-ipc-producer
spec:
  hostIPC: true
  hostPID: true
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-a100
  containers:
  - name: producer
    image: quay.io/harpatil/cuda-ipc:v6
    command: ["/usr/local/bin/producer"]
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      privileged: true
      capabilities:
        add: ["IPC_LOCK"]
