apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: cuda-ipc-scc
allowHostIPC: true
allowedCapabilities:
- IPC_LOCK
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
